---
title: "Uncertainty is central to reliable inference"
subtitle: "Trying out implementation in MPlus"
author: 
 - name: Björn S. Siepe
   orcid: 0000-0002-9558-4648
   affiliations: University of Marburg
 - name: Matthias Kloft
   orcid: 0000-0003-1845-6957
   affiliations: University of Marburg  
 - name: Daniel W. Heck
   orcid: 0000-0002-6302-9252
   affiliations: University of Marburg
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
    fig-width: 7
    fig-height: 4.5
    fig-align: "center"
    embed-resoureces: true
execute:
  message: false
  warning: false
---



# Background

Here, we try to implement an mlVAR model in Mplus using the `DSEM2R` resources available [online](https://github.com/secastroal/DSEM2R).


# Prep

Packages:
```{r}
library(tidyverse)
```



Source the scripts from the GitHub repo: 

```{r}
# find all R scripts in scripts/mplus/dsem2r
list.files("scripts/mplus/dsem2r", pattern = ".R$", full.names = TRUE) |> 
  lapply(source)
```



# Simple example

```{r}
mlvardata <- mlVAR::mlVARsim(nPerson = 50, 
                             nNode   = 3, 
                             nTime   = 100)
mlvardata <- mlvardata$Data
names(mlvardata) <- c("y1", "y2", "y3", "id")
```


Write to Mplus:

```{r}
exmlvar02 <- mlvar2Mplus(
  y    = c("y1", "y2", "y3"),
  id   = "id",
  data = mlvardata,
  random.effects = list(lagged = TRUE, rvar = FALSE),
  filename = "scripts/mplus/exmlvar02.dat")
```



This does not allow for covariance between innovations yet. 


