
# Old DGP for mlVARsim
Old DGPS with mlVAR_sim:
```{r dgps}
# Settings for data simulation
# for mlvar sim
thetaVar = 1
DF_theta = 2
mu_SD = c(1, 1)
init_beta_SD = c(0.3, 1.5) 
fixedMuSD = 1
shrink_fixed = 0.9
shrink_deviation = 0.9
pcor_sparsity = 0.5
beta_sparsity = 0.5

# for regression
reg_error_sd = 1

# Parameters
# sim_pars_old <- list(
#   reg_error_sd = reg_error_sd,
#   thetaVar = thetaVar,
#   DF_theta = DF_theta,
#   mu_SD = mu_SD,
#   init_beta_SD = init_beta_SD,
#   fixedMuSD = fixedMuSD,
#   shrink_fixed = shrink_fixed,
#   shrink_deviation = shrink_deviation
#   # mlvar_model = mlvar_model
# )
```



# Old sim summarize functions

```{r}
  
  
  rmse_beta_gvar <- summary_calc(results, "gvar", "fit_gvar", "beta", rmse_mean_list)
  rmse_pcor_gvar <- summary_calc(results, "gvar", "fit_gvar", "pcor", rmse_mean_list)
  mse_beta_gvar <- summary_calc(results, "gvar", "fit_gvar", "beta", mse_mean_list)
  mse_pcor_gvar <- summary_calc(results, "gvar", "fit_gvar", "pcor", mse_mean_list)
  
  rmse_beta_gimme <- summary_calc(results, "gimme", "fit_gimme", "beta", rmse_mean_list)
  rmse_pcor_gimme <- summary_calc(results, "gimme", "fit_gimme", "pcor", rmse_mean_list)
  mse_beta_gimme <- summary_calc(results, "gimme", "fit_gimme", "beta", mse_mean_list)
  mse_pcor_gimme <- summary_calc(results, "gimme", "fit_gimme", "pcor", mse_mean_list)
  
  rmse_beta_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "beta", rmse_mean_list)
  rmse_pcor_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "pcor", rmse_mean_list)
  mse_beta_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "beta", mse_mean_list)
  mse_pcor_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "pcor", mse_mean_list)
  
  rmse_beta_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "beta", rmse_mean_list)
  rmse_pcor_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "pcor", rmse_mean_list)
  mse_beta_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "beta", mse_mean_list)
  mse_pcor_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "pcor", mse_mean_list)
  
  
  
  
  
  #-- Summary and MCSE
  # Have to additionally estimate the MSE for the MCSE of the RMSE
  #- LASSO GVAR
  rmse_beta_gvar_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_gvar), c(1,2), as.numeric))  
  rmse_beta_gvar_mean <- mean(rmse_beta_gvar_mean_tmp)
  rmse_pcor_gvar_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_gvar), c(1,2), as.numeric))
  rmse_pcor_gvar_mean <- mean(rmse_pcor_gvar_mean_tmp)
  mse_beta_gvar_mean_tmp <- colMeans(apply(as.matrix(mse_beta_gvar), c(1,2), as.numeric))
  mse_beta_gvar_mean <- mean(mse_beta_gvar_mean_tmp)
  mse_pcor_gvar_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_gvar), c(1,2), as.numeric))
  mse_pcor_gvar_mean <- mean(mse_pcor_gvar_mean_tmp)
  
  rmse_beta_gvar_mcse <- sqrt(stats::var(rmse_beta_gvar_mean_tmp) / (4*n_rep*mse_beta_gvar_mean))
  rmse_pcor_gvar_mcse <- sqrt(stats::var(rmse_pcor_gvar_mean_tmp) / (4*n_rep*mse_pcor_gvar_mean))
  mse_beta_gvar_mcse <- sqrt(stats::var(mse_beta_gvar_mean_tmp) / n_rep)
  mse_pcor_gvar_mcse <- sqrt(stats::var(mse_pcor_gvar_mean_tmp) / n_rep)
  
  #- GIMME
  rmse_beta_gimme_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_gimme), c(1,2), as.numeric))
  rmse_beta_gimme_mean <- mean(rmse_beta_gimme_mean_tmp)
  rmse_pcor_gimme_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_gimme), c(1,2), as.numeric))
  rmse_pcor_gimme_mean <- mean(rmse_pcor_gimme_mean_tmp)
  mse_beta_gimme_mean_tmp <- colMeans(apply(as.matrix(mse_beta_gimme), c(1,2), as.numeric))
  mse_beta_gimme_mean <- mean(mse_beta_gimme_mean_tmp)
  mse_pcor_gimme_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_gimme), c(1,2), as.numeric))
  mse_pcor_gimme_mean <- mean(mse_pcor_gimme_mean_tmp)
  
  rmse_beta_gimme_mcse <- sqrt(stats::var(rmse_beta_gimme_mean_tmp) / (4*n_rep*mse_beta_gimme_mean))
  rmse_pcor_gimme_mcse <- sqrt(stats::var(rmse_pcor_gimme_mean_tmp) / (4*n_rep*mse_pcor_gimme_mean))
  mse_beta_gimme_mcse <- sqrt(stats::var(mse_beta_gimme_mean_tmp) / n_rep)
  mse_pcor_gimme_mcse <- sqrt(stats::var(mse_pcor_gimme_mean_tmp) / n_rep)
  
  #- mlVAR
  rmse_beta_mlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_mlvar), c(1,2), as.numeric))
  rmse_beta_mlvar_mean <- mean(rmse_beta_mlvar_mean_tmp)
  rmse_pcor_mlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_mlvar), c(1,2), as.numeric))
  rmse_pcor_mlvar_mean <- mean(rmse_pcor_mlvar_mean_tmp)
  mse_beta_mlvar_mean_tmp <- colMeans(apply(as.matrix(mse_beta_mlvar), c(1,2), as.numeric))
  mse_beta_mlvar_mean <- mean(mse_beta_mlvar_mean_tmp)
  mse_pcor_mlvar_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_mlvar), c(1,2), as.numeric))
  mse_pcor_mlvar_mean <- mean(mse_pcor_mlvar_mean_tmp)
  
  rmse_beta_mlvar_mcse <- sqrt(stats::var(rmse_beta_mlvar_mean_tmp) / (4*n_rep*mse_beta_mlvar_mean))
  rmse_pcor_mlvar_mcse <- sqrt(stats::var(rmse_pcor_mlvar_mean_tmp) / (4*n_rep*mse_pcor_mlvar_mean))
  mse_beta_mlvar_mcse <- sqrt(stats::var(mse_beta_mlvar_mean_tmp) / n_rep)
  mse_pcor_mlvar_mcse <- sqrt(stats::var(mse_pcor_mlvar_mean_tmp) / n_rep)
  
  
  #- BmlVar 
  rmse_beta_bmlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_bmlvar), c(1,2), as.numeric))
  rmse_beta_bmlvar_mean <- mean(rmse_beta_bmlvar_mean_tmp)
  rmse_pcor_bmlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_bmlvar), c(1,2), as.numeric))
  rmse_pcor_bmlvar_mean <- mean(rmse_pcor_bmlvar_mean_tmp)
  mse_beta_bmlvar_mean_tmp <- colMeans(apply(as.matrix(mse_beta_bmlvar), c(1,2), as.numeric))
  mse_beta_bmlvar_mean <- mean(mse_beta_bmlvar_mean_tmp)
  mse_pcor_bmlvar_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_bmlvar), c(1,2), as.numeric))
  mse_pcor_bmlvar_mean <- mean(mse_pcor_bmlvar_mean_tmp)
  
  rmse_beta_bmlvar_mcse <- sqrt(stats::var(rmse_beta_bmlvar_mean_tmp) / (4*n_rep*mse_beta_bmlvar_mean))
  rmse_pcor_bmlvar_mcse <- sqrt(stats::var(rmse_pcor_bmlvar_mean_tmp) / (4*n_rep*mse_pcor_bmlvar_mean))
  mse_beta_bmlvar_mcse <- sqrt(stats::var(mse_beta_bmlvar_mean_tmp) / n_rep)
  mse_pcor_bmlvar_mcse <- sqrt(stats::var(mse_pcor_bmlvar_mean_tmp) / n_rep)
  
  
  
  
  

  

  #-- Bias
  #- LASSO GVAR
  bias_beta_gvar <- summary_calc(results, "gvar", "fit_gvar", "beta", bias_mean_list)
  bias_pcor_gvar <- summary_calc(results, "gvar", "fit_gvar", "pcor", bias_mean_list)
  
  bias_beta_gimme <- summary_calc(results, "gimme", "fit_gimme", "beta", bias_mean_list)
  bias_pcor_gimme <- summary_calc(results, "gimme", "fit_gimme", "pcor", bias_mean_list)
  
  bias_beta_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "beta", bias_mean_list)
  bias_pcor_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "pcor", bias_mean_list)
  
  bias_beta_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "beta", bias_mean_list)
  bias_pcor_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "pcor", bias_mean_list)
  
    
  
  
  #-- MCSE
  bias_beta_gvar_mean <- calc_mean(bias_beta_gvar)
  bias_pcor_gvar_mean <- calc_mean(bias_pcor_gvar)
  bias_beta_gvar_mcse <- sqrt(stats::var(bias_beta_gvar_mean) / n_rep)
  bias_pcor_gvar_mcse <- sqrt(stats::var(bias_pcor_gvar_mean) / n_rep)
  
  bias_beta_gimme_mean <- calc_mean(bias_beta_gimme)
  bias_pcor_gimme_mean <- calc_mean(bias_pcor_gimme)
  bias_beta_gimme_mcse <- sqrt(stats::var(bias_beta_gimme_mean) / n_rep)
  bias_pcor_gimme_mcse <- sqrt(stats::var(bias_pcor_gimme_mean) / n_rep)
  
  bias_beta_mlvar_mean <- calc_mean(bias_beta_mlvar)
  bias_pcor_mlvar_mean <- calc_mean(bias_pcor_mlvar)
  bias_beta_mlvar_mcse <- sqrt(stats::var(bias_beta_mlvar_mean) / n_rep)
  bias_pcor_mlvar_mcse <- sqrt(stats::var(bias_pcor_mlvar_mean) / n_rep)
  
  bias_beta_bmlvar_mean <- calc_mean(bias_beta_bmlvar)
  bias_pcor_bmlvar_mean <- calc_mean(bias_pcor_bmlvar)
  bias_beta_bmlvar_mcse <- sqrt(stats::var(bias_beta_bmlvar_mean) / n_rep)
  bias_pcor_bmlvar_mcse <- sqrt(stats::var(bias_pcor_bmlvar_mean) / n_rep)
  
  
  
  rankcor_beta_gvar <- calc_correlation(results, "gvar", "temp")
  rankcor_pcor_gvar <- calc_correlation(results, "gvar", "cont")
  rankcor_beta_gimme <- calc_correlation(results, "gimme", "temp")
  rankcor_pcor_gimme <- calc_correlation(results, "gimme", "cont")
  rankcor_beta_mlvar <- calc_correlation(results, "mlvar", "temp")
  rankcor_pcor_mlvar <- calc_correlation(results, "mlvar", "cont")
  rankcor_beta_bmlvar <- calc_correlation(results, "bmlvar", "temp")
  rankcor_pcor_bmlvar <- calc_correlation(results, "bmlvar", "cont")
  
  

  rankcor_beta_gvar_mcse <- bootstrap_rankcor(rankcor_beta_gvar, n_rep)
  rankcor_pcor_gvar_mcse <- bootstrap_rankcor(rankcor_pcor_gvar, n_rep)
  rankcor_beta_gimme_mcse <- bootstrap_rankcor(rankcor_beta_gimme, n_rep)
  rankcor_pcor_gimme_mcse <- bootstrap_rankcor(rankcor_pcor_gimme, n_rep)
  rankcor_beta_mlvar_mcse <- bootstrap_rankcor(rankcor_beta_mlvar, n_rep)
  rankcor_pcor_mlvar_mcse <- bootstrap_rankcor(rankcor_pcor_mlvar, n_rep)
  rankcor_beta_bmlvar_mcse <- bootstrap_rankcor(rankcor_beta_bmlvar, n_rep)
  rankcor_pcor_bmlvar_mcse <- bootstrap_rankcor(rankcor_pcor_bmlvar, n_rep)
    
  
  
  power_reg_tempdens_gvar <- regression_power(results, "gvar", "tempdens")
  power_reg_contdens_gvar <- regression_power(results, "gvar", "contdens")
  power_reg_outstrength_gvar <- regression_power(results, "gvar", "outstrength")
  
  power_reg_tempdens_gimme <- regression_power(results, "gimme", "tempdens")
  power_reg_contdens_gimme <- regression_power(results, "gimme", "contdens")
  power_reg_outstrength_gimme <- regression_power(results, "gimme", "outstrength")
  
  power_reg_tempdens_mlvar <- regression_power(results, "mlvar", "tempdens")
  power_reg_contdens_mlvar <- regression_power(results, "mlvar", "contdens")
  power_reg_outstrength_mlvar <- regression_power(results, "mlvar", "outstrength")
  
  power_reg_tempdens_bmlvar <- regression_power(results, "bmlvar", "tempdens")
  power_reg_contdens_bmlvar <- regression_power(results, "bmlvar", "contdens")
  power_reg_outstrength_bmlvar <- regression_power(results, "bmlvar", "outstrength")
  
  
  #-- MCSE
  # rowMeans due to the three underlying conditions
  power_reg_tempdens_gvar_mean <- rowMeans(power_reg_tempdens_gvar)
  power_reg_contdens_gvar_mean <- rowMeans(power_reg_contdens_gvar)
  power_reg_outstrength_gvar_mean <- rowMeans(power_reg_outstrength_gvar)
  power_reg_tempdens_gvar_mcse <- sqrt(power_reg_tempdens_gvar_mean * (1 - power_reg_tempdens_gvar_mean) / n_rep)
  power_reg_contdens_gvar_mcse <- sqrt(power_reg_contdens_gvar_mean * (1 - power_reg_contdens_gvar_mean) / n_rep)
  power_reg_outstrength_gvar_mcse <- sqrt(power_reg_outstrength_gvar_mean * (1 - power_reg_outstrength_gvar_mean) / n_rep)
  
  power_reg_tempdens_gimme_mean <- rowMeans(power_reg_tempdens_gimme)
  power_reg_contdens_gimme_mean <- rowMeans(power_reg_contdens_gimme)
  power_reg_outstrength_gimme_mean <- rowMeans(power_reg_outstrength_gimme)
  power_reg_tempdens_gimme_mcse <- sqrt(power_reg_tempdens_gimme_mean * (1 - power_reg_tempdens_gimme_mean) / n_rep)
  power_reg_contdens_gimme_mcse <- sqrt(power_reg_contdens_gimme_mean * (1 - power_reg_contdens_gimme_mean) / n_rep)
  power_reg_outstrength_gimme_mcse <- sqrt(power_reg_outstrength_gimme_mean * (1 - power_reg_outstrength_gimme_mean) / n_rep)

  power_reg_tempdens_mlvar_mean <- rowMeans(power_reg_tempdens_mlvar)
  power_reg_contdens_mlvar_mean <- rowMeans(power_reg_contdens_mlvar)
  power_reg_outstrength_mlvar_mean <- rowMeans(power_reg_outstrength_mlvar)
  power_reg_tempdens_mlvar_mcse <- sqrt(power_reg_tempdens_mlvar_mean * (1 - power_reg_tempdens_mlvar_mean) / n_rep)
  power_reg_contdens_mlvar_mcse <- sqrt(power_reg_contdens_mlvar_mean * (1 - power_reg_contdens_mlvar_mean) / n_rep)
  power_reg_outstrength_mlvar_mcse <- sqrt(power_reg_outstrength_mlvar_mean * (1 - power_reg_outstrength_mlvar_mean) / n_rep)

  power_reg_tempdens_bmlvar_mean <- rowMeans(power_reg_tempdens_bmlvar)
  power_reg_contdens_bmlvar_mean <- rowMeans(power_reg_contdens_bmlvar)
  power_reg_outstrength_bmlvar_mean <- rowMeans(power_reg_outstrength_bmlvar)
  power_reg_tempdens_bmlvar_mcse <- sqrt(power_reg_tempdens_bmlvar_mean * (1 - power_reg_tempdens_bmlvar_mean) / n_rep)
  power_reg_contdens_bmlvar_mcse <- sqrt(power_reg_contdens_bmlvar_mean * (1 - power_reg_contdens_bmlvar_mean) / n_rep)
  power_reg_outstrength_bmlvar_mcse <- sqrt(power_reg_outstrength_bmlvar_mean * (1 - power_reg_outstrength_bmlvar_mean) / n_rep)

  
  
  
  
  mostcent_beta_gvar <- calc_most_cent_ident(results, "gvar", "outstrength")
  mostcent_pcor_gvar <- calc_most_cent_ident(results, "gvar", "strength")
  mostcent_beta_gimme <- calc_most_cent_ident(results, "gimme", "outstrength")
  mostcent_pcor_gimme <- calc_most_cent_ident(results, "gimme", "strength")
  mostcent_beta_mlvar <- calc_most_cent_ident(results, "mlvar", "outstrength")
  mostcent_pcor_mlvar <- calc_most_cent_ident(results, "mlvar", "strength")
  mostcent_beta_bmlvar <- calc_most_cent_ident(results, "bmlvar", "outstrength")
  mostcent_pcor_bmlvar <- calc_most_cent_ident(results, "bmlvar", "strength")

  #-- Most central MCSE
  mostcent_beta_gvar_mean <- mean(mostcent_beta_gvar)
  mostcent_pcor_gvar_mean <- mean(mostcent_pcor_gvar)
  mostcent_beta_gvar_mcse <- sqrt(mostcent_beta_gvar_mean * (1 - mostcent_beta_gvar_mean) / n_rep)
  mostcent_pcor_gvar_mcse <- sqrt(mostcent_pcor_gvar_mean * (1 - mostcent_pcor_gvar_mean) / n_rep)
  mostcent_beta_gimme_mean <- mean(mostcent_beta_gimme)
  mostcent_pcor_gimme_mean <- mean(mostcent_pcor_gimme)
  mostcent_beta_gimme_mcse <- sqrt(mostcent_beta_gimme_mean * (1 - mostcent_beta_gimme_mean) / n_rep)
  mostcent_pcor_gimme_mcse <- sqrt(mostcent_pcor_gimme_mean * (1 - mostcent_pcor_gimme_mean) / n_rep)
  mostcent_beta_mlvar_mean <- mean(mostcent_beta_mlvar)
  mostcent_pcor_mlvar_mean <- mean(mostcent_pcor_mlvar)
  mostcent_beta_mlvar_mcse <- sqrt(mostcent_beta_mlvar_mean * (1 - mostcent_beta_mlvar_mean) / n_rep)
  mostcent_pcor_mlvar_mcse <- sqrt(mostcent_pcor_mlvar_mean * (1 - mostcent_pcor_mlvar_mean) / n_rep)
  mostcent_beta_bmlvar_mean <- mean(mostcent_beta_bmlvar)
  mostcent_pcor_bmlvar_mean <- mean(mostcent_pcor_bmlvar)
  mostcent_beta_bmlvar_mcse <- sqrt(mostcent_beta_bmlvar_mean * (1 - mostcent_beta_bmlvar_mean) / n_rep)
  mostcent_pcor_bmlvar_mcse <- sqrt(mostcent_pcor_bmlvar_mean * (1 - mostcent_pcor_bmlvar_mean) / n_rep)
  
  
  
  
  
  
  
   #- LASSO GVAR
  rmse_reg_tempdens_gvar <- regression_rmse(results, "gvar", "tempdens", rmse = TRUE)
  rmse_reg_contdens_gvar <- regression_rmse(results, "gvar", "contdens", rmse = TRUE)
  rmse_reg_outstrength_gvar <- regression_rmse(results, "gvar", "outstrength", rmse = TRUE)
  mse_reg_tempdens_gvar <- regression_rmse(results, "gvar", "tempdens", rmse = FALSE)
  mse_reg_contdens_gvar <- regression_rmse(results, "gvar", "contdens", rmse = FALSE)
  mse_reg_outstrength_gvar <- regression_rmse(results, "gvar", "outstrength", rmse = FALSE)
  
    
  #- GIMME
  rmse_reg_tempdens_gimme <- regression_rmse(results, "gimme", "tempdens", rmse = TRUE)
  rmse_reg_contdens_gimme <- regression_rmse(results, "gimme", "contdens", rmse = TRUE)
  rmse_reg_outstrength_gimme <- regression_rmse(results, "gimme", "outstrength", rmse = TRUE)
  mse_reg_tempdens_gimme <- regression_rmse(results, "gimme", "tempdens", rmse = FALSE)
  mse_reg_contdens_gimme <- regression_rmse(results, "gimme", "contdens", rmse = FALSE)
  mse_reg_outstrength_gimme <- regression_rmse(results, "gimme", "outstrength", rmse = FALSE)
  
  
  #- mlVAR
  rmse_reg_tempdens_mlvar <- regression_rmse(results, "mlvar", "tempdens", rmse = TRUE)
  rmse_reg_contdens_mlvar <- regression_rmse(results, "mlvar", "contdens", rmse = TRUE)
  rmse_reg_outstrength_mlvar <- regression_rmse(results, "mlvar", "outstrength", rmse = TRUE)
  mse_reg_tempdens_mlvar <- regression_rmse(results, "mlvar", "tempdens", rmse = FALSE)
  mse_reg_contdens_mlvar <- regression_rmse(results, "mlvar", "contdens", rmse = FALSE)
  mse_reg_outstrength_mlvar <- regression_rmse(results, "mlvar", "outstrength", rmse = FALSE)
    
  #- BmlVar
  rmse_reg_tempdens_bmlvar <- regression_rmse(results, "bmlvar", "tempdens", rmse = TRUE)
  rmse_reg_contdens_bmlvar <- regression_rmse(results, "bmlvar", "contdens", rmse = TRUE)
  rmse_reg_outstrength_bmlvar <- regression_rmse(results, "bmlvar", "outstrength", rmse = TRUE)
  mse_reg_tempdens_bmlvar <- regression_rmse(results, "bmlvar", "tempdens", rmse = FALSE)
  mse_reg_contdens_bmlvar <- regression_rmse(results, "bmlvar", "contdens", rmse = FALSE)
  mse_reg_outstrength_bmlvar <- regression_rmse(results, "bmlvar", "outstrength", rmse = FALSE)
  
    
  #-- MCSE
  #- LASSO GVAR
  rmse_reg_tempdens_gvar_mean <- rowMeans(rmse_reg_tempdens_gvar, na.rm = TRUE)
  rmse_reg_contdens_gvar_mean <- rowMeans(rmse_reg_contdens_gvar, na.rm = TRUE)
  rmse_reg_outstrength_gvar_mean <- rowMeans(rmse_reg_outstrength_gvar, na.rm = TRUE)
  mse_reg_tempdens_gvar_mean <- rowMeans(mse_reg_tempdens_gvar, na.rm = TRUE)
  mse_reg_contdens_gvar_mean <- rowMeans(mse_reg_contdens_gvar, na.rm = TRUE)
  mse_reg_outstrength_gvar_mean <- rowMeans(mse_reg_outstrength_gvar, na.rm = TRUE)
  
  rmse_reg_tempdens_gvar_mcse <- sqrt ( apply(rmse_reg_tempdens_gvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_gvar_mean))
  rmse_reg_contdens_gvar_mcse <- sqrt ( apply(rmse_reg_contdens_gvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_gvar_mean))
  rmse_reg_outstrength_gvar_mcse <- sqrt ( apply(rmse_reg_outstrength_gvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_gvar_mean))
    
  #- GIMME
  rmse_reg_tempdens_gimme_mean <- rowMeans(rmse_reg_tempdens_gimme, na.rm = TRUE)
  rmse_reg_contdens_gimme_mean <- rowMeans(rmse_reg_contdens_gimme, na.rm = TRUE)
  rmse_reg_outstrength_gimme_mean <- rowMeans(rmse_reg_outstrength_gimme, na.rm = TRUE)
  mse_reg_tempdens_gimme_mean <- rowMeans(mse_reg_tempdens_gimme, na.rm = TRUE)
  mse_reg_contdens_gimme_mean <- rowMeans(mse_reg_contdens_gimme, na.rm = TRUE)
  mse_reg_outstrength_gimme_mean <- rowMeans(mse_reg_outstrength_gimme, na.rm = TRUE)
  
  rmse_reg_tempdens_gimme_mcse <- sqrt ( apply(rmse_reg_tempdens_gimme, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_gimme_mean))
  rmse_reg_contdens_gimme_mcse <- sqrt ( apply(rmse_reg_contdens_gimme, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_gimme_mean))
  rmse_reg_outstrength_gimme_mcse <- sqrt ( apply(rmse_reg_outstrength_gimme, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_gimme_mean))
  
  
  #- mlVAR
  rmse_reg_tempdens_mlvar_mean <- rowMeans(rmse_reg_tempdens_mlvar, na.rm = TRUE)
  rmse_reg_contdens_mlvar_mean <- rowMeans(rmse_reg_contdens_mlvar, na.rm = TRUE)
  rmse_reg_outstrength_mlvar_mean <- rowMeans(rmse_reg_outstrength_mlvar, na.rm = TRUE)
  mse_reg_tempdens_mlvar_mean <- rowMeans(mse_reg_tempdens_mlvar, na.rm = TRUE)
  mse_reg_contdens_mlvar_mean <- rowMeans(mse_reg_contdens_mlvar, na.rm = TRUE)
  mse_reg_outstrength_mlvar_mean <- rowMeans(mse_reg_outstrength_mlvar, na.rm = TRUE)
    
  rmse_reg_tempdens_mlvar_mcse <- sqrt ( apply(rmse_reg_tempdens_mlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_mlvar_mean))
  rmse_reg_contdens_mlvar_mcse <- sqrt ( apply(rmse_reg_contdens_mlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_mlvar_mean))
  rmse_reg_outstrength_mlvar_mcse <- sqrt ( apply(rmse_reg_outstrength_mlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_mlvar_mean))
  
    
  #- BmlVar
  rmse_reg_tempdens_bmlvar_mean <- rowMeans(rmse_reg_tempdens_bmlvar, na.rm = TRUE)
  rmse_reg_contdens_bmlvar_mean <- rowMeans(rmse_reg_contdens_bmlvar, na.rm = TRUE)
  rmse_reg_outstrength_bmlvar_mean <- rowMeans(rmse_reg_outstrength_bmlvar, na.rm = TRUE)
  mse_reg_tempdens_bmlvar_mean <- rowMeans(mse_reg_tempdens_bmlvar, na.rm = TRUE)
  mse_reg_contdens_bmlvar_mean <- rowMeans(mse_reg_contdens_bmlvar, na.rm = TRUE)
  mse_reg_outstrength_bmlvar_mean <- rowMeans(mse_reg_outstrength_bmlvar, na.rm = TRUE)
  
  rmse_reg_tempdens_bmlvar_mcse <- sqrt ( apply(rmse_reg_tempdens_bmlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_bmlvar_mean))
  rmse_reg_contdens_bmlvar_mcse <- sqrt ( apply(rmse_reg_contdens_bmlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_bmlvar_mean))
  rmse_reg_outstrength_bmlvar_mcse <- sqrt ( apply(rmse_reg_outstrength_bmlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_bmlvar_mean))
```




# Old mock simulation

We now temporarily create a mock results data frame which we use to create visualization templates.

```{r mock-results}
sim_res <- readRDS(here("output/pilot_sim_results.RDS"))

# duplicate the first row of the dataframe multiple times
sim_res[2:4,] <- sim_res[1,]

# create mock conditions
sim_res$dgp[2:4] <- c("nonsparse", "sparse", "nonsparse")
sim_res$heterogeneity[2:4] <- c("high", "high", "low")

# Add some random noise for visualization tests
# define non-performance columns
exclude_cols <- c("dgp", "heterogeneity", "REPLICATIONS", "SIM_TIME", "RAM_USED", "SEED", "COMPLETED", "WARNINGS")
# Define the column strings to exclude from the non-negativity constraint
exclude_nonneg <- c("mse", "rankcor", "bias")
noise_cols <- setdiff(colnames(sim_res), exclude_cols)

# Add noise to rows 2-4 for the selected columns
sim_res[2:4, noise_cols] <- sapply(sim_res[2:4, noise_cols], function(x) x * (1 + runif(length(x), -0.1, 0.3)))


nonneg_cols <- noise_cols[!grepl("mse|rankcor|bias", noise_cols)]
# Apply non-negativity constraint to rows 2-4 for the selected columns
sim_res[2:4, nonneg_cols] <- sapply(sim_res[2:4, nonneg_cols], function(x) pmax(x, 0))



```


# Old renaming in simulation dataframe

```{r}
#   # THIS IS TEMPORARY UNTIL A RENAMING OF THE REGRESSION COLUMNS!
#   # AND UNTIL RENAMING OF THE RANKCOR
#   # TODO
#   # TODO
#   # filter out all rows that contain "mean1", "mean2", "mean3", "mcse1", "mcse2", "mcse3" in "measure"
#   filter(!str_detect(measure, "mean1|mean2|mean3|mcse1|mcse2|mcse3")) %>%
#     separate_wider_delim(measure, 
#                        delim = "_", 
#                        names = c("pm", "outcome", "method", "summary")) %>%
#   filter(pm != "rankcor") %>% 
#   # END TEMPORARY
```

