---
title: "Using features of dynamic networks to guide treatment selection and outcome prediction"
subtitle: "Additional Simulations (Revision 2): Node Count and Sparsity"
author: 
 - name: Björn S. Siepe
   orcid: 0000-0002-9558-4648
   affiliations: University of Marburg
 - name: Matthias Kloft
   orcid: 0000-0003-1845-6957
   affiliations: University of Marburg  
 - name: Fridtjof Petersen
   orcid: 0000-0002-4913-8532
   affiliations: University of Groningen
 - name: Yong Zhang
   orcid: 0000-0002-6313-2575
   affiliations: University of Groningen
 - name: Laura F. Bringmann
   orcid: 0000-0002-8091-9935
   affiliations: University of Groningen
 - name: Daniel W. Heck
   orcid: 0000-0002-6302-9252
   affiliations: University of Marburg
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
    fig-width: 7
    fig-height: 4.5
    fig-align: "center"
    embed-resources: true
execute:
  message: false
  warning: false
  eval: false # only show code
---

# Background

In this document, we combine the various files for the additional simulations and analyze them together.


# Preparation

Load relevant packages:

```{r}
library(tidyverse)
library(SimDesign)
library(cowplot)
library(showtext)
library(sysfonts)
library(ggokabeito)
library(janitor)
library(ggh4x)
library(pander)
library(MetBrewer)
library(here)
library(lm.beta)

source(here::here("scripts", "00_functions.R"))
```


We then load the simulation results. Due to the computational complexity of the simulation, these are spread across different files: 







# Session Info


```{r session-info}
pander::pander(sessionInfo())
```

