---
title: "Centrality Simulation"
format: html
---

# Background
This script contains the `SimDesign` code for the simulation study. 

We first load all relevant packages: 
```{r packages}
library(tidyverse)
library(SimDesign)
library(mlVAR)
library(graphicalVAR)
library(gimme)
library(here)
source(here("scripts", "functions.R"))
# source(here("scripts", "MLVAR_fit_stan_wrapper.qmd"))

```




# Data Generation

## Data-Generating Processes

Old DGPS with mlVAR_sim:
```{r dgps}
# Settings for data simulation
# for mlvar sim
thetaVar = 1
DF_theta = 2
mu_SD = c(1, 1)
init_beta_SD = c(0.3, 1.5) 
fixedMuSD = 1
shrink_fixed = 0.9
shrink_deviation = 0.9
pcor_sparsity = 0.5
beta_sparsity = 0.5

# for regression
reg_error_sd = 1

# Parameters
# sim_pars_old <- list(
#   reg_error_sd = reg_error_sd,
#   thetaVar = thetaVar,
#   DF_theta = DF_theta,
#   mu_SD = mu_SD,
#   init_beta_SD = init_beta_SD,
#   fixedMuSD = fixedMuSD,
#   shrink_fixed = shrink_fixed,
#   shrink_deviation = shrink_deviation
#   # mlvar_model = mlvar_model
# )
```


New DGP with specific graph: 
```{r}
# non-sparse Graph to simulate from
graph_nonsparse <- readRDS(here("data/graph_nonsparse.RDS"))

# sparse DGP
graph_sparse <- readRDS(here("data/graph_sparse.RDS"))
```



## Setting parameters
```{r params}
# Simulation parameters
# Number of individuals 
n_id <- 200

# Number of variables
n_var <- 6

# Number of timepoints
n_tp <- 150

# random effects sds
beta_sd <- 0.1
kappa_sd <- 0.1

# Type of DGP
dgp <- c("sparse", "dense")

# Heterogeneity
heterogeneity <- c("low", "high")

# # Strength of the correlation
# hard-coded down below
# beta_reg <- c(0, 0.2, 0.4)



# Design
df_design <- SimDesign::createDesign(
  dgp = dgp,
  heterogeneity = heterogeneity
  )



sim_pars <- list(
  n_id = n_id,
  n_var = n_var,
  n_tp = n_tp,
  reg_error_sd = reg_error_sd,
  beta_sd = beta_sd,
  kappa_sd = kappa_sd,
  graph_nonsparse = graph_nonsparse,
  graph_sparse = graph_sparse
)
```



## Simulating Data
```{r data-generation}
sim_generate <- function(condition, fixed_objects = NULL){
  
  # obtain fixed params
  SimDesign::Attach(fixed_objects)

  dgp_graph <- ifelse(condition$dgp == "sparse", 
                      "graph_sparse", 
                      "graph_nonsparse")
  # beta_sd <- ifelse(condition$heterogeneity == "low", 
  #                   0.1, 
  #                   0.3)
  # kappa_sd <- ifelse(condition$heterogeneity == "low", 
  #                    0.3, 
  #                    0.9)
  
  ml_sim <- sim_gvar_loop(
                     graph = fixed_objects[[dgp_graph]],
                     beta_sd = beta_sd,
                     kappa_sd = kappa_sd,
                     n_person = n_id,
                     n_time = n_tp,
                     n_node = n_var,
                     max_try = 10000,
                     listify = TRUE)
  
  # Obtain true centralities
  true_cent <- centrality_mlvar_sim(ml_sim,
                                    sim_fn = "sim_gvar_loop")
  
  # TODO think about if scaling is okay here
  tempdens <- unlist(true_cent$dens_temp) |> scale()
  outstrength <- sapply(true_cent$outstrength, `[`, 1) |> scale()
  contdens <- unlist(true_cent$dens_cont) |> scale()
  
  
  # Simulate covariate with certain error
  eps_sd <- reg_error_sd

  # Simulate error
  resid_dens <- rnorm(n_id, mean = 0, sd = eps_sd)
  resid_cent <- rnorm(n_id, mean = 0, sd = eps_sd)

  # covariate_tempdens = rep(condition$beta_reg, condition$n_id) * tempdens + resid_dens
  # covariate_oustrength = rep(condition$beta_reg, condition$n_id) * outstrength + resid_cent
  # correlation matrix of true effects
  rho <- c(
          1, 0, .2, .4,
          0, 1, 0, 0,
         .2, 0, 1, 0,
         .4, 0 , 0, 1) |> matrix(4, 4, byrow = T)
  
  # cholesky decomposition of rho
  L <- chol(rho)
  
  # Generate covariates with multiple levels of correlation
  covariate_temp_dens <- cbind(tempdens, 
                               rnorm(n_id), 
                               rnorm(n_id),
                               rnorm(n_id))
  covariate_cont_dens <- cbind(contdens, 
                               rnorm(n_id), 
                               rnorm(n_id),
                               rnorm(n_id))
  covariate_out_strength <- cbind(outstrength, 
                                  rnorm(n_id), 
                                  rnorm(n_id),
                                  rnorm(n_id))
  
  covariate_temp_dens <- covariate_temp_dens %*% L
  covariate_cont_dens <- covariate_cont_dens %*% L
  covariate_out_strength <- covariate_out_strength %*% L
  
  # Return data and true centralities
  ret_data <- list(
    data = ml_sim$data,
    beta = ml_sim$beta_l,
    kappa = ml_sim$kappa_l,
    pcor = ml_sim$pcor_l,
    covariate_temp_dens = covariate_temp_dens,
    covariate_out_strength = covariate_out_strength,
    covariate_cont_dens = covariate_cont_dens,
    true_cent = true_cent
  )
  
  return(ret_data)
  
  
}

```


# Analysis

```{r data-analysis}
sim_analyse <- function(condition, dat, fixed_objects = NULL){
  
  #--- Preparation
  SimDesign::Attach(fixed_objects)
  
  # Concatenate list of data into dataframe with id column
  df_data <- dplyr::bind_rows(purrr::map(dat$data, dplyr::as_tibble)
                              , .id = "ID") 
  
  
  
  #--- graphicalVAR
  # Fit models
  fit_gvar <- lapply(dat$data, function(x){
    graphicalVAR::graphicalVAR(x, 
                               nLambda = 50,
                               verbose = FALSE,
                               gamma = 0, 
                               scale = FALSE)
  })
 
  
  # Obtain centralities, IDs nested in list
  cent_gvar <- purrr::transpose(lapply(fit_gvar, function(x){
    centrality_gvar(x)
  }))

  
  dens_temp_gvar <- unlist(cent_gvar$dens_temp)
  dens_cont_gvar <- unlist(cent_gvar$dens_cont)
  outstrength_gvar <- lapply(cent_gvar$outstrength, function(x) unname(x))
  strength_gvar <- lapply(cent_gvar$strength, function(x) unname(x))
  outstrength_gvar_first <- sapply(cent_gvar$outstrength, function(x) unname(x[1]))
  
  # Create list of subject-specific estimates
  beta_gvar <- lapply(fit_gvar, function(x){
    t(x$beta[,-1])
  })
  pcor_gvar <- lapply(fit_gvar, function(x){
    x$PCC
  })
  
  # Fit regression
  reg_gvar_temp_dens <- lapply(2:4, function(i) lm(dat$covariate_temp_dens[, i] ~ dens_temp_gvar))
  reg_gvar_cont_dens <- lapply(2:4, function(i) lm(dat$covariate_cont_dens[, i] ~ dens_cont_gvar))
  reg_gvar_out_strength <- lapply(2:4, function(i) lm(dat$covariate_out_strength[, i] ~ outstrength_gvar_first))
  
  #--- GIMME
  
  # Fit model
  fit_gimme <- gimme::gimme(dat$data,
                            ar = TRUE,
                            subgroup = TRUE,
                            plot = FALSE,
                            hybrid = FALSE,
                            groupcutoff = .50,
                            subcutoff = .50)
  
  cent_gimme <- centrality_gimme(fit_gimme)

  # Obtain centralities
  dens_temp_gimme <- unlist(cent_gimme$dens_temp)
  dens_cont_gimme <- unlist(cent_gimme$dens_cont)
  outstrength_gimme <- lapply(cent_gimme$outstrength, function(x) unname(x))
  strength_gimme <- lapply(cent_gimme$strength, function(x) unname(x))
  outstrength_gimme_first <- sapply(cent_gimme$outstrength, function(x) unname(x[1]))
  
  # Create list of subject-specific estimates
  beta_gimme <- lapply(fit_gimme$path_est_mats, function(x){
    t(x[,1:n_var])
  })
  pcor_gimme <- lapply(fit_gimme$path_est_mats, function(x){
    x[, (n_var+1):(n_var*2)]
  })

  # Fit regression
  reg_gimme_temp_dens <- lapply(2:4, function(i) lm(dat$covariate_temp_dens[, i] ~ dens_temp_gimme))
  reg_gimme_cont_dens <- lapply(2:4, function(i) lm(dat$covariate_cont_dens[, i] ~ dens_cont_gimme))
  reg_gimme_out_strength <- lapply(2:4, function(i) lm(dat$covariate_out_strength[, i] ~ outstrength_gimme_first))

  # #--- frequentist mlVAR

  # Fit model
  fit_mlvar <- mlVAR::mlVAR(df_data,
                            vars = c("V1", "V2", "V3", "V4", "V5", "V6"),
                            idvar = "ID",
                            estimator = "lmer",
                            contemporaneous = "correlated",
                            temporal = "correlated",
                            nCores = 1,
                            scale = FALSE)

  # Obtain centralities
  cent_mlvar <- centrality_mlvar(fit_mlvar)
  dens_temp_mlvar <- unlist(cent_mlvar$dens_temp)
  dens_cont_mlvar <- unlist(cent_mlvar$dens_cont)
  outstrength_mlvar <- lapply(cent_mlvar$outstrength, function(x) unname(x))
  strength_mlvar <- lapply(cent_mlvar$strength, function(x) unname(x))
  outstrength_mlvar_first <- sapply(cent_mlvar$outstrength, function(x) unname(x[1]))
  
  # Create list of subject-specific estimates
  beta_mlvar <- lapply(1:n_id, function(i){
    mlVAR::getNet(fit_mlvar,
                  subject = i,
                  type = "temporal")
  })
  pcor_mlvar <- lapply(1:n_id, function(i){
    mlVAR::getNet(fit_mlvar,
                  subject = i,
                  type = "contemporaneous")
  })

  # Fit regression
  reg_mlvar_temp_dens <- lapply(2:4, function(i) lm(dat$covariate_temp_dens[, i] ~ dens_temp_mlvar))
  reg_mlvar_cont_dens <- lapply(2:4, function(i) lm(dat$covariate_cont_dens[, i] ~ dens_cont_mlvar))
  reg_mlvar_out_strength <- lapply(2:4, function(i) lm(dat$covariate_out_strength[, i] ~ outstrength_mlvar_first))
  # 
  #--- Bayesian mlVAR
  
  # Fit model
  # fit_blmvar <- fit_mlvar_stan(
  #                df_data,
  #                regression_outcome,
  #                n_person = n_id,
  #                n_var = n_var,
  #                n_timepoints = n_tp,
  #                n_chains = 4,
  #                n_cores = 1,
  #                # "variational" or "sampling"
  #                method = "variational",
  #                stan_model_compiled = mlvar_model
  #                )
  
  # Obtain centralities
  # cent_bmlvar <- centrality_bmlvar(fit_bmlvar)
  # dens_temp_blmvar <- unlist(cent_blmvar$dens_temp)
  # dens_cont_blmvar <- unlist(cent_blmvar$dens_cont)
  # outstrength_blmvar <- lapply(cent_blmvar$outstrength, function(x) unname(x))
  # strength_blmvar <- lapply(cent_blmvar$strength, function(x) unname(x))
  # outstrength_blmvar_first <- sapply(cent_blmvar$outstrength, function(x) unname(x[1]))

  # Obtain regression coefficients
  # TODO
  
  # TODO save summary 
  # summary_blmvar <- summary(fit_blmvar)
  
  #--- Return Results
  # Also return true centralities for comparison later
  ret_results <- list(
    gvar = list(
      fit_gvar = list(
        beta = beta_gvar,
        pcor = pcor_gvar),
      dens_temp = dens_temp_gvar,
      dens_cont = dens_cont_gvar,
      outstrength = outstrength_gvar,
      strength = strength_gvar,
      reg_tempdens = reg_gvar_temp_dens,
      reg_contdens = reg_gvar_cont_dens,
      reg_outstrength = reg_gvar_out_strength
    ),
    gimme = list(
      fit_gimme = list(
        beta = beta_gimme,
        pcor = pcor_gimme
      ),
      dens_temp = dens_temp_gimme,
      dens_cont = dens_cont_gimme,
      outstrength = outstrength_gimme,
      strength = strength_gimme,
      reg_tempdens = reg_gimme_temp_dens,
      reg_contdens = reg_gimme_cont_dens,
      reg_outstrength = reg_gimme_out_strength
    ),
    mlvar = list(
      fit_mlvar = list(
        beta = beta_mlvar,
        pcor = pcor_mlvar),
      dens_temp = dens_temp_mlvar,
      dens_cont = dens_cont_mlvar,
      outstrength = outstrength_mlvar,
      strength = strength_mlvar,
      reg_tempdens = reg_mlvar_temp_dens,
      reg_contdens = reg_mlvar_cont_dens,
      reg_outstrength = reg_mlvar_out_strength
    ),
    # bmlvar = list(
    #   fit_blmvar = fit_blmvar,
    #   dens_temp = dens_temp_bmlvar,
    #   outstrength = outstrength_bmlvar,
    #   strength = strength_bmlvar,
    #   reg_tempdens = reg_bmlvar_tempdens,
    #   reg_outstrength = reg_bmlvar_outstrength
    # ),
    true_cent = dat$true_cent,
    data = dat$data,
    beta = dat$beta,
    kappa = dat$kappa,
    pcor = dat$pcor
  )
  return(ret_results)
  
}

```



# Summary


```{r summarize}
sim_summarise <- function(condition, results, fixed_objects = NULL){
  
  #--- Preparation
  SimDesign::Attach(fixed_objects)

  #--- Parameter recovery  
  # IMPORTANT: Keep in mind structure of mlVARsim object (rows vs. cols)
  #-- RMSE
  # TODO move this function to auxiliary file
  summary_calc <- function(results, method, fit, measure, func) {
  sapply(seq_along(results), function(i){
    if(is.null(results[[i]][[method]][[fit]])){
      return(NA)
    } 
    else{
      unlist(func(results[[i]][[method]][[fit]][[measure]], results[[i]][[measure]]))
    }
  })
}
  
  
  rmse_beta_gvar <- summary_calc(results, "gvar", "fit_gvar", "beta", rmse_mean_list)
  rmse_pcor_gvar <- summary_calc(results, "gvar", "fit_gvar", "pcor", rmse_mean_list)
  mse_beta_gvar <- summary_calc(results, "gvar", "fit_gvar", "beta", mse_mean_list)
  mse_pcor_gvar <- summary_calc(results, "gvar", "fit_gvar", "pcor", mse_mean_list)
  
  rmse_beta_gimme <- summary_calc(results, "gimme", "fit_gimme", "beta", rmse_mean_list)
  rmse_pcor_gimme <- summary_calc(results, "gimme", "fit_gimme", "pcor", rmse_mean_list)
  mse_beta_gimme <- summary_calc(results, "gimme", "fit_gimme", "beta", mse_mean_list)
  mse_pcor_gimme <- summary_calc(results, "gimme", "fit_gimme", "pcor", mse_mean_list)
  
  rmse_beta_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "beta", rmse_mean_list)
  rmse_pcor_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "pcor", rmse_mean_list)
  mse_beta_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "beta", mse_mean_list)
  mse_pcor_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "pcor", mse_mean_list)
  
  rmse_beta_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "beta", rmse_mean_list)
  rmse_pcor_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "pcor", rmse_mean_list)
  mse_beta_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "beta", mse_mean_list)
  mse_pcor_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "pcor", mse_mean_list)
  
  #-- Summary and MCSE
  # Have to additionally estimate the MSE for the MCSE of the RMSE
  #- LASSO GVAR
  rmse_beta_gvar_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_gvar), c(1,2), as.numeric))  
  rmse_beta_gvar_mean <- mean(rmse_beta_gvar_mean_tmp)
  rmse_pcor_gvar_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_gvar), c(1,2), as.numeric))
  rmse_pcor_gvar_mean <- mean(rmse_pcor_gvar_mean_tmp)
  mse_beta_gvar_mean_tmp <- colMeans(apply(as.matrix(mse_beta_gvar), c(1,2), as.numeric))
  mse_beta_gvar_mean <- mean(mse_beta_gvar_mean_tmp)
  mse_pcor_gvar_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_gvar), c(1,2), as.numeric))
  mse_pcor_gvar_mean <- mean(mse_pcor_gvar_mean_tmp)
  
  rmse_beta_gvar_mcse <- sqrt(stats::var(rmse_beta_gvar_mean_tmp) / (4*n_rep*mse_beta_gvar_mean))
  rmse_pcor_gvar_mcse <- sqrt(stats::var(rmse_pcor_gvar_mean_tmp) / (4*n_rep*mse_pcor_gvar_mean))
  mse_beta_gvar_mcse <- sqrt(stats::var(mse_beta_gvar_mean_tmp) / n_rep)
  mse_pcor_gvar_mcse <- sqrt(stats::var(mse_pcor_gvar_mean_tmp) / n_rep)
  
  #- GIMME
  rmse_beta_gimme_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_gimme), c(1,2), as.numeric))
  rmse_beta_gimme_mean <- mean(rmse_beta_gimme_mean_tmp)
  rmse_pcor_gimme_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_gimme), c(1,2), as.numeric))
  rmse_pcor_gimme_mean <- mean(rmse_pcor_gimme_mean_tmp)
  mse_beta_gimme_mean_tmp <- colMeans(apply(as.matrix(mse_beta_gimme), c(1,2), as.numeric))
  mse_beta_gimme_mean <- mean(mse_beta_gimme_mean_tmp)
  mse_pcor_gimme_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_gimme), c(1,2), as.numeric))
  mse_pcor_gimme_mean <- mean(mse_pcor_gimme_mean_tmp)
  
  rmse_beta_gimme_mcse <- sqrt(stats::var(rmse_beta_gimme_mean_tmp) / (4*n_rep*mse_beta_gimme_mean))
  rmse_pcor_gimme_mcse <- sqrt(stats::var(rmse_pcor_gimme_mean_tmp) / (4*n_rep*mse_pcor_gimme_mean))
  mse_beta_gimme_mcse <- sqrt(stats::var(mse_beta_gimme_mean_tmp) / n_rep)
  mse_pcor_gimme_mcse <- sqrt(stats::var(mse_pcor_gimme_mean_tmp) / n_rep)
  
  #- mlVAR
  rmse_beta_mlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_mlvar), c(1,2), as.numeric))
  rmse_beta_mlvar_mean <- mean(rmse_beta_mlvar_mean_tmp)
  rmse_pcor_mlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_mlvar), c(1,2), as.numeric))
  rmse_pcor_mlvar_mean <- mean(rmse_pcor_mlvar_mean_tmp)
  mse_beta_mlvar_mean_tmp <- colMeans(apply(as.matrix(mse_beta_mlvar), c(1,2), as.numeric))
  mse_beta_mlvar_mean <- mean(mse_beta_mlvar_mean_tmp)
  mse_pcor_mlvar_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_mlvar), c(1,2), as.numeric))
  mse_pcor_mlvar_mean <- mean(mse_pcor_mlvar_mean_tmp)
  
  rmse_beta_mlvar_mcse <- sqrt(stats::var(rmse_beta_mlvar_mean_tmp) / (4*n_rep*mse_beta_mlvar_mean))
  rmse_pcor_mlvar_mcse <- sqrt(stats::var(rmse_pcor_mlvar_mean_tmp) / (4*n_rep*mse_pcor_mlvar_mean))
  mse_beta_mlvar_mcse <- sqrt(stats::var(mse_beta_mlvar_mean_tmp) / n_rep)
  mse_pcor_mlvar_mcse <- sqrt(stats::var(mse_pcor_mlvar_mean_tmp) / n_rep)
  
  
  #- BmlVar 
  rmse_beta_bmlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_beta_bmlvar), c(1,2), as.numeric))
  rmse_beta_bmlvar_mean <- mean(rmse_beta_bmlvar_mean_tmp)
  rmse_pcor_bmlvar_mean_tmp <- colMeans(apply(as.matrix(rmse_pcor_bmlvar), c(1,2), as.numeric))
  rmse_pcor_bmlvar_mean <- mean(rmse_pcor_bmlvar_mean_tmp)
  mse_beta_bmlvar_mean_tmp <- colMeans(apply(as.matrix(mse_beta_bmlvar), c(1,2), as.numeric))
  mse_beta_bmlvar_mean <- mean(mse_beta_bmlvar_mean_tmp)
  mse_pcor_bmlvar_mean_tmp <- colMeans(apply(as.matrix(mse_pcor_bmlvar), c(1,2), as.numeric))
  mse_pcor_bmlvar_mean <- mean(mse_pcor_bmlvar_mean_tmp)
  
  rmse_beta_bmlvar_mcse <- sqrt(stats::var(rmse_beta_bmlvar_mean_tmp) / (4*n_rep*mse_beta_bmlvar_mean))
  rmse_pcor_bmlvar_mcse <- sqrt(stats::var(rmse_pcor_bmlvar_mean_tmp) / (4*n_rep*mse_pcor_bmlvar_mean))
  mse_beta_bmlvar_mcse <- sqrt(stats::var(mse_beta_bmlvar_mean_tmp) / n_rep)
  mse_pcor_bmlvar_mcse <- sqrt(stats::var(mse_pcor_bmlvar_mean_tmp) / n_rep)
  
  
  
  # # Simplifying the calculation  
  # calc_mean <- function(result) {
  # tmp <- colMeans(apply(as.matrix(result), c(1,2), as.numeric))
  # mean(tmp)
  # }
  # methods <- c("gvar", "gimme", "mlvar", "bmlvar")
  # measures <- c("beta", "pcor")
  # pms <- c("rmse", "mse")
  # combinations <- expand.grid(method = methods, measure = measures, pm = pms)
  # 
  # # Use calc_mean for each combination
  # results_list <- apply(combinations, 1, function(x) {
  #   result <- get(paste0(x['pm'], "_", x['measure'], "_", x['method']))
  #   calc_mean(result)
  # })  
  # names(results_list) <- apply(combinations, 1, function(x) {
  # paste0(x['pm'], "_", x['measure'], "_", x['method'], "_mean")
  # })
    
  #-- Bias
  #- LASSO GVAR
  bias_beta_gvar <- summary_calc(results, "gvar", "fit_gvar", "beta", bias_mean_list)
  bias_pcor_gvar <- summary_calc(results, "gvar", "fit_gvar", "pcor", bias_mean_list)
  
  bias_beta_gimme <- summary_calc(results, "gimme", "fit_gimme", "beta", bias_mean_list)
  bias_pcor_gimme <- summary_calc(results, "gimme", "fit_gimme", "pcor", bias_mean_list)
  
  bias_beta_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "beta", bias_mean_list)
  bias_pcor_mlvar <- summary_calc(results, "mlvar", "fit_mlvar", "pcor", bias_mean_list)
  
  bias_beta_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "beta", bias_mean_list)
  bias_pcor_bmlvar <- summary_calc(results, "bmlvar", "fit_bmlvar", "pcor", bias_mean_list)
  
    
  #-- MCSE
  bias_beta_gvar_mean <- calc_mean(bias_beta_gvar)
  bias_pcor_gvar_mean <- calc_mean(bias_pcor_gvar)
  bias_beta_gvar_mcse <- sqrt(stats::var(bias_beta_gvar_mean) / n_rep)
  bias_pcor_gvar_mcse <- sqrt(stats::var(bias_pcor_gvar_mean) / n_rep)
  
  bias_beta_gimme_mean <- calc_mean(bias_beta_gimme)
  bias_pcor_gimme_mean <- calc_mean(bias_pcor_gimme)
  bias_beta_gimme_mcse <- sqrt(stats::var(bias_beta_gimme_mean) / n_rep)
  bias_pcor_gimme_mcse <- sqrt(stats::var(bias_pcor_gimme_mean) / n_rep)
  
  bias_beta_mlvar_mean <- calc_mean(bias_beta_mlvar)
  bias_pcor_mlvar_mean <- calc_mean(bias_pcor_mlvar)
  bias_beta_mlvar_mcse <- sqrt(stats::var(bias_beta_mlvar_mean) / n_rep)
  bias_pcor_mlvar_mcse <- sqrt(stats::var(bias_pcor_mlvar_mean) / n_rep)
  
  bias_beta_bmlvar_mean <- calc_mean(bias_beta_bmlvar)
  bias_pcor_bmlvar_mean <- calc_mean(bias_pcor_bmlvar)
  bias_beta_bmlvar_mcse <- sqrt(stats::var(bias_beta_bmlvar_mean) / n_rep)
  bias_pcor_bmlvar_mcse <- sqrt(stats::var(bias_pcor_bmlvar_mean) / n_rep)
  
    
  #--- Centrality
  #-- Rank-Order between individuals
  calc_correlation <- function(results, method, measure) {
  sapply(seq_along(results), function(i){
    if(is.null(results[[i]][[method]][[paste0("fit_", method)]])){
      return(NA)
    } 
    else{
      stats::cor(results[[i]][[method]][[paste0("dens_", measure)]], 
                 unlist(results[[i]]$true_cent[[paste0("dens_", measure)]]), 
                 method = "spearman")
    }
  })
  }
  rankcor_beta_gvar <- calc_correlation(results, "gvar", "temp")
  rankcor_pcor_gvar <- calc_correlation(results, "gvar", "cont")
  rankcor_beta_gimme <- calc_correlation(results, "gimme", "temp")
  rankcor_pcor_gimme <- calc_correlation(results, "gimme", "cont")
  rankcor_beta_mlvar <- calc_correlation(results, "mlvar", "temp")
  rankcor_pcor_mlvar <- calc_correlation(results, "mlvar", "cont")
  rankcor_beta_bmlvar <- calc_correlation(results, "bmlvar", "temp")
  rankcor_pcor_bmlvar <- calc_correlation(results, "bmlvar", "cont")
  
  
  # Rank-order MCSE
  # create bootstrapped correlation standard error
  # This was unnecessary, I bootstrap simulation replications
  # not data sets... should get another coffee
  # cor_boot <- function(data, i){
  #     cor(data[i,1], data[i,2], method = "spearman", use = "pairwise")
  #   }
  # calc_bootcor <- function(results, method, measure) {
  #   sapply(seq_along(results), function(i){
  #     if(is.null(results[[i]][[method]][[paste0("fit_", method)]])){
  #       return(NA)
  #     } 
  #     else{
  #       cor_dat <- cbind(results[[i]][[method]][[paste0("dens_", measure)]], 
  #               unlist(results[[i]]$true_cent[[paste0("dens_", measure)]]))
  #       boot_res <- boot::boot(
  #         data = cor_dat, 
  #         statistic = cor_boot,
  #         R = 1000)
  #     }
  #     # return standard error
  #     sd(boot_res$t)
  #   })
  # }
  bootstrap_rankcor <- function(data, n_boot){
    bootstrap_res <- vector("numeric", n_boot)
    for(i in 1:n_boot){
      ind <- sample(1:n_boot, replace = TRUE)
      bootstrap_res[i] <- mean(data[ind], na.rm = TRUE)
    }
      sd(bootstrap_res, na.rm = TRUE)
  }
  rankcor_beta_gvar_mcse <- bootstrap_rankcor(rankcor_beta_gvar, n_rep)
  rankcor_pcor_gvar_mcse <- bootstrap_rankcor(rankcor_pcor_gvar, n_rep)
  rankcor_beta_gimme_mcse <- bootstrap_rankcor(rankcor_beta_gimme, n_rep)
  rankcor_pcor_gimme_mcse <- bootstrap_rankcor(rankcor_pcor_gimme, n_rep)
  rankcor_beta_mlvar_mcse <- bootstrap_rankcor(rankcor_beta_mlvar, n_rep)
  rankcor_pcor_mlvar_mcse <- bootstrap_rankcor(rankcor_pcor_mlvar, n_rep)
  rankcor_beta_bmlvar_mcse <- bootstrap_rankcor(rankcor_beta_bmlvar, n_rep)
  rankcor_pcor_bmlvar_mcse <- bootstrap_rankcor(rankcor_pcor_bmlvar, n_rep)
  
    
  #-- Most central within individuals
  calc_most_cent_ident <- function(results, method, measure) {
    sapply(seq_along(results), function(i){
      if(is.null(results[[i]][[method]][paste0("fit_", method)])){
        return(NA)
      } 
      else{
        mci <- most_cent_ident(results[[i]][[method]][[measure]], 
                              results[[i]]$true_cent[[measure]])
        colSums(matrix(unlist(mci), 
                      nrow = n_id, 
                      byrow = FALSE))/n_id
      }
    })
  }
  mostcent_beta_gvar <- calc_most_cent_ident(results, "gvar", "outstrength")
  mostcent_pcor_gvar <- calc_most_cent_ident(results, "gvar", "strength")
  mostcent_beta_gimme <- calc_most_cent_ident(results, "gimme", "outstrength")
  mostcent_pcor_gimme <- calc_most_cent_ident(results, "gimme", "strength")
  mostcent_beta_mlvar <- calc_most_cent_ident(results, "mlvar", "outstrength")
  mostcent_pcor_mlvar <- calc_most_cent_ident(results, "mlvar", "strength")
  mostcent_beta_bmlvar <- calc_most_cent_ident(results, "bmlvar", "outstrength")
  mostcent_pcor_bmlvar <- calc_most_cent_ident(results, "bmlvar", "strength")

  #-- Most central MCSE
  mostcent_beta_gvar_mean <- mean(mostcent_beta_gvar)
  mostcent_pcor_gvar_mean <- mean(mostcent_pcor_gvar)
  mostcent_beta_gvar_mcse <- sqrt(mostcent_beta_gvar_mean * (1 - mostcent_beta_gvar_mean) / n_rep)
  mostcent_pcor_gvar_mcse <- sqrt(mostcent_pcor_gvar_mean * (1 - mostcent_pcor_gvar_mean) / n_rep)
  mostcent_beta_gimme_mean <- mean(mostcent_beta_gimme)
  mostcent_pcor_gimme_mean <- mean(mostcent_pcor_gimme)
  mostcent_beta_gimme_mcse <- sqrt(mostcent_beta_gimme_mean * (1 - mostcent_beta_gimme_mean) / n_rep)
  mostcent_pcor_gimme_mcse <- sqrt(mostcent_pcor_gimme_mean * (1 - mostcent_pcor_gimme_mean) / n_rep)
  mostcent_beta_mlvar_mean <- mean(mostcent_beta_mlvar)
  mostcent_pcor_mlvar_mean <- mean(mostcent_pcor_mlvar)
  mostcent_beta_mlvar_mcse <- sqrt(mostcent_beta_mlvar_mean * (1 - mostcent_beta_mlvar_mean) / n_rep)
  mostcent_pcor_mlvar_mcse <- sqrt(mostcent_pcor_mlvar_mean * (1 - mostcent_pcor_mlvar_mean) / n_rep)
  mostcent_beta_bmlvar_mean <- mean(mostcent_beta_bmlvar)
  mostcent_pcor_bmlvar_mean <- mean(mostcent_pcor_bmlvar)
  mostcent_beta_bmlvar_mcse <- sqrt(mostcent_beta_bmlvar_mean * (1 - mostcent_beta_bmlvar_mean) / n_rep)
  mostcent_pcor_bmlvar_mcse <- sqrt(mostcent_pcor_bmlvar_mean * (1 - mostcent_pcor_bmlvar_mean) / n_rep)

  
  
  #--- Regression
  #-- Power
  regression_power <- function(results, 
                               method, 
                               measure,
                               true_coef = c(0,.2,.4),
                               lm_beta = TRUE) {
  sapply(seq_along(results), function(i){
    if(is.null(results[[i]][[method]][[paste0("reg_", measure)]])){
      return(NA)
    } 
    else{
      reg_pvals <- sapply(results[[i]][[method]][[paste0("reg_", measure)]],
                          function(x){
                            if(isTRUE(lm_beta)){
                              res <- summary(lm.beta::lm.beta(x))$coefficients
                              res[2,5]
                            } else{
                              res <- summary(x)$coefficients
                              res[2,4]
                            }})

      # Calculate Empirical detection rate/power
      ifelse(reg_pvals < .05, 1, 0)
    }
  })
  }
  power_reg_tempdens_gvar <- regression_power(results, "gvar", "tempdens")
  power_reg_contdens_gvar <- regression_power(results, "gvar", "contdens")
  power_reg_outstrength_gvar <- regression_power(results, "gvar", "outstrength")
  
  power_reg_tempdens_gimme <- regression_power(results, "gimme", "tempdens")
  power_reg_contdens_gimme <- regression_power(results, "gimme", "contdens")
  power_reg_outstrength_gimme <- regression_power(results, "gimme", "outstrength")
  
  power_reg_tempdens_mlvar <- regression_power(results, "mlvar", "tempdens")
  power_reg_contdens_mlvar <- regression_power(results, "mlvar", "contdens")
  power_reg_outstrength_mlvar <- regression_power(results, "mlvar", "outstrength")
  
  power_reg_tempdens_bmlvar <- regression_power(results, "bmlvar", "tempdens")
  power_reg_contdens_bmlvar <- regression_power(results, "bmlvar", "contdens")
  power_reg_outstrength_bmlvar <- regression_power(results, "bmlvar", "outstrength")
  
  
  #-- MCSE
  # rowMeans due to the three underlying conditions
  power_reg_tempdens_gvar_mean <- rowMeans(power_reg_tempdens_gvar)
  power_reg_contdens_gvar_mean <- rowMeans(power_reg_contdens_gvar)
  power_reg_outstrength_gvar_mean <- rowMeans(power_reg_outstrength_gvar)
  power_reg_tempdens_gvar_mcse <- sqrt(power_reg_tempdens_gvar_mean * (1 - power_reg_tempdens_gvar_mean) / n_rep)
  power_reg_contdens_gvar_mcse <- sqrt(power_reg_contdens_gvar_mean * (1 - power_reg_contdens_gvar_mean) / n_rep)
  power_reg_outstrength_gvar_mcse <- sqrt(power_reg_outstrength_gvar_mean * (1 - power_reg_outstrength_gvar_mean) / n_rep)
  
  power_reg_tempdens_gimme_mean <- rowMeans(power_reg_tempdens_gimme)
  power_reg_contdens_gimme_mean <- rowMeans(power_reg_contdens_gimme)
  power_reg_outstrength_gimme_mean <- rowMeans(power_reg_outstrength_gimme)
  power_reg_tempdens_gimme_mcse <- sqrt(power_reg_tempdens_gimme_mean * (1 - power_reg_tempdens_gimme_mean) / n_rep)
  power_reg_contdens_gimme_mcse <- sqrt(power_reg_contdens_gimme_mean * (1 - power_reg_contdens_gimme_mean) / n_rep)
  power_reg_outstrength_gimme_mcse <- sqrt(power_reg_outstrength_gimme_mean * (1 - power_reg_outstrength_gimme_mean) / n_rep)

  power_reg_tempdens_mlvar_mean <- rowMeans(power_reg_tempdens_mlvar)
  power_reg_contdens_mlvar_mean <- rowMeans(power_reg_contdens_mlvar)
  power_reg_outstrength_mlvar_mean <- rowMeans(power_reg_outstrength_mlvar)
  power_reg_tempdens_mlvar_mcse <- sqrt(power_reg_tempdens_mlvar_mean * (1 - power_reg_tempdens_mlvar_mean) / n_rep)
  power_reg_contdens_mlvar_mcse <- sqrt(power_reg_contdens_mlvar_mean * (1 - power_reg_contdens_mlvar_mean) / n_rep)
  power_reg_outstrength_mlvar_mcse <- sqrt(power_reg_outstrength_mlvar_mean * (1 - power_reg_outstrength_mlvar_mean) / n_rep)

  power_reg_tempdens_bmlvar_mean <- rowMeans(power_reg_tempdens_bmlvar)
  power_reg_contdens_bmlvar_mean <- rowMeans(power_reg_contdens_bmlvar)
  power_reg_outstrength_bmlvar_mean <- rowMeans(power_reg_outstrength_bmlvar)
  power_reg_tempdens_bmlvar_mcse <- sqrt(power_reg_tempdens_bmlvar_mean * (1 - power_reg_tempdens_bmlvar_mean) / n_rep)
  power_reg_contdens_bmlvar_mcse <- sqrt(power_reg_contdens_bmlvar_mean * (1 - power_reg_contdens_bmlvar_mean) / n_rep)
  power_reg_outstrength_bmlvar_mcse <- sqrt(power_reg_outstrength_bmlvar_mean * (1 - power_reg_outstrength_bmlvar_mean) / n_rep)



  
  
  
  
  #-- RMSE
  true_coef <- c(0, .2, .4)
  regression_rmse <- function(results, 
                              method, 
                              measure,
                              true_coef = c(0,.2,.4),
                              lm_beta = TRUE,
                              rmse = TRUE) {
  sapply(seq_along(results), function(i){
    if(is.null(results[[i]][[method]][[paste0("reg_", measure)]])){
      return(NA)
    } 
    else{
      reg_coefs <- sapply(results[[i]][[method]][[paste0("reg_", measure)]],
                          function(x){
                            if(isTRUE(lm_beta)){
                              lm.beta::lm.beta(x)$standardized.coefficients
                            } else{
                              x$coefficients
                            }})[2,]   # 2nd row -> beta coef
      # Calculate RMSE
      if(isTRUE(rmse)){
        sqrt( (reg_coefs - true_coef )^2 )
      } else{
        (reg_coefs - true_coef)^2
      }
      
      }
  })
  }
  
  #- LASSO GVAR
  rmse_reg_tempdens_gvar <- regression_rmse(results, "gvar", "tempdens", rmse = TRUE)
  rmse_reg_contdens_gvar <- regression_rmse(results, "gvar", "contdens", rmse = TRUE)
  rmse_reg_outstrength_gvar <- regression_rmse(results, "gvar", "outstrength", rmse = TRUE)
  mse_reg_tempdens_gvar <- regression_rmse(results, "gvar", "tempdens", rmse = FALSE)
  mse_reg_contdens_gvar <- regression_rmse(results, "gvar", "contdens", rmse = FALSE)
  mse_reg_outstrength_gvar <- regression_rmse(results, "gvar", "outstrength", rmse = FALSE)
  
    
  #- GIMME
  rmse_reg_tempdens_gimme <- regression_rmse(results, "gimme", "tempdens", rmse = TRUE)
  rmse_reg_contdens_gimme <- regression_rmse(results, "gimme", "contdens", rmse = TRUE)
  rmse_reg_outstrength_gimme <- regression_rmse(results, "gimme", "outstrength", rmse = TRUE)
  mse_reg_tempdens_gimme <- regression_rmse(results, "gimme", "tempdens", rmse = FALSE)
  mse_reg_contdens_gimme <- regression_rmse(results, "gimme", "contdens", rmse = FALSE)
  mse_reg_outstrength_gimme <- regression_rmse(results, "gimme", "outstrength", rmse = FALSE)
  
  
  #- mlVAR
  rmse_reg_tempdens_mlvar <- regression_rmse(results, "mlvar", "tempdens", rmse = TRUE)
  rmse_reg_contdens_mlvar <- regression_rmse(results, "mlvar", "contdens", rmse = TRUE)
  rmse_reg_outstrength_mlvar <- regression_rmse(results, "mlvar", "outstrength", rmse = TRUE)
  mse_reg_tempdens_mlvar <- regression_rmse(results, "mlvar", "tempdens", rmse = FALSE)
  mse_reg_contdens_mlvar <- regression_rmse(results, "mlvar", "contdens", rmse = FALSE)
  mse_reg_outstrength_mlvar <- regression_rmse(results, "mlvar", "outstrength", rmse = FALSE)
    
  #- BmlVar
  rmse_reg_tempdens_bmlvar <- regression_rmse(results, "bmlvar", "tempdens", rmse = TRUE)
  rmse_reg_contdens_bmlvar <- regression_rmse(results, "bmlvar", "contdens", rmse = TRUE)
  rmse_reg_outstrength_bmlvar <- regression_rmse(results, "bmlvar", "outstrength", rmse = TRUE)
  mse_reg_tempdens_bmlvar <- regression_rmse(results, "bmlvar", "tempdens", rmse = FALSE)
  mse_reg_contdens_bmlvar <- regression_rmse(results, "bmlvar", "contdens", rmse = FALSE)
  mse_reg_outstrength_bmlvar <- regression_rmse(results, "bmlvar", "outstrength", rmse = FALSE)
  
    
  #-- MCSE
  #- LASSO GVAR
  rmse_reg_tempdens_gvar_mean <- rowMeans(rmse_reg_tempdens_gvar, na.rm = TRUE)
  rmse_reg_contdens_gvar_mean <- rowMeans(rmse_reg_contdens_gvar, na.rm = TRUE)
  rmse_reg_outstrength_gvar_mean <- rowMeans(rmse_reg_outstrength_gvar, na.rm = TRUE)
  mse_reg_tempdens_gvar_mean <- rowMeans(mse_reg_tempdens_gvar, na.rm = TRUE)
  mse_reg_contdens_gvar_mean <- rowMeans(mse_reg_contdens_gvar, na.rm = TRUE)
  mse_reg_outstrength_gvar_mean <- rowMeans(mse_reg_outstrength_gvar, na.rm = TRUE)
  
  rmse_reg_tempdens_gvar_mcse <- sqrt ( apply(rmse_reg_tempdens_gvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_gvar))
  rmse_reg_contdens_gvar_mcse <- sqrt ( apply(rmse_reg_contdens_gvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_gvar))
  rmse_reg_outstrength_gvar_mcse <- sqrt ( apply(rmse_reg_outstrength_gvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_gvar))
    
  #- GIMME
  rmse_reg_tempdens_gimme_mean <- rowMeans(rmse_reg_tempdens_gimme, na.rm = TRUE)
  rmse_reg_contdens_gimme_mean <- rowMeans(rmse_reg_contdens_gimme, na.rm = TRUE)
  rmse_reg_outstrength_gimme_mean <- rowMeans(rmse_reg_outstrength_gimme, na.rm = TRUE)
  mse_reg_tempdens_gimme_mean <- rowMeans(mse_reg_tempdens_gimme, na.rm = TRUE)
  mse_reg_contdens_gimme_mean <- rowMeans(mse_reg_contdens_gimme, na.rm = TRUE)
  mse_reg_outstrength_gimme_mean <- rowMeans(mse_reg_outstrength_gimme, na.rm = TRUE)
  
  rmse_reg_tempdens_gimme_mcse <- sqrt ( apply(rmse_reg_tempdens_gimme, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_gimme))
  rmse_reg_contdens_gimme_mcse <- sqrt ( apply(rmse_reg_contdens_gimme, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_gimme))
  rmse_reg_outstrength_gimme_mcse <- sqrt ( apply(rmse_reg_outstrength_gimme, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_gimme))
  
  
  #- mlVAR
  rmse_reg_tempdens_mlvar_mean <- rowMeans(rmse_reg_tempdens_mlvar, na.rm = TRUE)
  rmse_reg_contdens_mlvar_mean <- rowMeans(rmse_reg_contdens_mlvar, na.rm = TRUE)
  rmse_reg_outstrength_mlvar_mean <- rowMeans(rmse_reg_outstrength_mlvar, na.rm = TRUE)
  mse_reg_tempdens_mlvar_mean <- rowMeans(mse_reg_tempdens_mlvar, na.rm = TRUE)
  mse_reg_contdens_mlvar_mean <- rowMeans(mse_reg_contdens_mlvar, na.rm = TRUE)
  mse_reg_outstrength_mlvar_mean <- rowMeans(mse_reg_outstrength_mlvar, na.rm = TRUE)
    
  rmse_reg_tempdens_mlvar_mcse <- sqrt ( apply(rmse_reg_tempdens_mlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_mlvar))
  rmse_reg_contdens_mlvar_mcse <- sqrt ( apply(rmse_reg_contdens_mlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_mlvar))
  rmse_reg_outstrength_mlvar_mcse <- sqrt ( apply(rmse_reg_outstrength_mlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_mlvar))
  
    
  #- BmlVar
  rmse_reg_tempdens_bmlvar_mean <- rowMeans(rmse_reg_tempdens_bmlvar, na.rm = TRUE)
  rmse_reg_contdens_bmlvar_mean <- rowMeans(rmse_reg_contdens_bmlvar, na.rm = TRUE)
  rmse_reg_outstrength_bmlvar_mean <- rowMeans(rmse_reg_outstrength_bmlvar, na.rm = TRUE)
  mse_reg_tempdens_bmlvar_mean <- rowMeans(mse_reg_tempdens_bmlvar, na.rm = TRUE)
  mse_reg_contdens_bmlvar_mean <- rowMeans(mse_reg_contdens_bmlvar, na.rm = TRUE)
  mse_reg_outstrength_bmlvar_mean <- rowMeans(mse_reg_outstrength_bmlvar, na.rm = TRUE)
  
  rmse_reg_tempdens_bmlvar_mcse <- sqrt ( apply(rmse_reg_tempdens_bmlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_tempdens_bmlvar))
  rmse_reg_contdens_bmlvar_mcse <- sqrt ( apply(rmse_reg_contdens_bmlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_contdens_bmlvar))
  rmse_reg_outstrength_bmlvar_mcse <- sqrt ( apply(rmse_reg_outstrength_bmlvar, 1, var, na.rm = TRUE) / (4*n_rep*mse_reg_outstrength_bmlvar))
  
  
  
  #--- Return
  # TODO not fully finished yet
  ret <- c(
    rmse_beta_gvar_mean = rmse_beta_gvar_mean,
    rmse_beta_gvar_mcse = rmse_beta_gvar_mcse,
    rmse_beta_gimme_mean = rmse_beta_gimme_mean,
    rmse_beta_gimme_mcse = rmse_beta_gimme_mcse,
    rmse_beta_mlvar_mean = rmse_beta_mlvar_mean,
    rmse_beta_mlvar_mcse = rmse_beta_mlvar_mcse,
    rmse_beta_bmlvar_mean = rmse_beta_bmlvar_mean,
    rmse_beta_bmlvar_mcse = rmse_beta_bmlvar_mcse,
    rmse_pcor_gvar_mean = rmse_pcor_gvar_mean,
    rmse_pcor_gvar_mcse = rmse_pcor_gvar_mcse,
    rmse_pcor_gimme_mean = rmse_pcor_gimme_mean,
    rmse_pcor_gimme_mcse = rmse_pcor_gimme_mcse,
    rmse_pcor_mlvar_mean = rmse_pcor_mlvar_mean,
    rmse_pcor_mlvar_mcse = rmse_pcor_mlvar_mcse,
    rmse_pcor_bmlvar_mean = rmse_pcor_bmlvar_mean,
    rmse_pcor_bmlvar_mcse = rmse_pcor_bmlvar_mcse,
    power_reg_tempdens_gvar = power_reg_tempdens_gvar,
    power_reg_contdens_gvar = power_reg_contdens_gvar,
    power_reg_outstrength_gvar = power_reg_outstrength_gvar,
    power_reg_tempdens_gimme = power_reg_tempdens_gimme,
    power_reg_contdens_gimme = power_reg_contdens_gimme,
    power_reg_outstrength_gimme = power_reg_outstrength_gimme,
    power_reg_tempdens_mlvar = power_reg_tempdens_mlvar,
    power_reg_contdens_mlvar = power_reg_contdens_mlvar,
    power_reg_outstrength_mlvar = power_reg_outstrength_mlvar,
    power_reg_tempdens_bmlvar = power_reg_tempdens_bmlvar,
    power_reg_contdens_bmlvar = power_reg_contdens_bmlvar,
    power_reg_outstrength_bmlvar = power_reg_outstrength_bmlvar,
    rmse_reg_tempdens_gvar = rmse_reg_tempdens_gvar,
    rmse_reg_contdens_gvar = rmse_reg_contdens_gvar,
    rmse_reg_outstrength_gvar = rmse_reg_outstrength_gvar,
    rmse_reg_tempdens_gimme = rmse_reg_tempdens_gimme,
    rmse_reg_contdens_gimme = rmse_reg_contdens_gimme,
    rmse_reg_outstrength_gimme = rmse_reg_outstrength_gimme,
    rmse_reg_tempdens_mlvar = rmse_reg_tempdens_mlvar,
    rmse_reg_contdens_mlvar = rmse_reg_contdens_mlvar,
    rmse_reg_outstrength_mlvar = rmse_reg_outstrength_mlvar,
    rmse_reg_tempdens_bmlvar = rmse_reg_tempdens_bmlvar,
    rmse_reg_contdens_bmlvar = rmse_reg_contdens_bmlvar,
    rmse_reg_outstrength_bmlvar = rmse_reg_outstrength_bmlvar
  )
  
  
  
  
}


```


# Executing Simulation

```{r run-sim}
# For testing
df_design_test <- df_design[1,]
sim_pars$n_id <- 25

n_rep <- 2
sim_results <- SimDesign::runSimulation(
                                    design = df_design_test, 
                                    replications = n_rep, 
                                    generate = sim_generate, 
                                    analyse = sim_analyse, 
                                    summarise = sim_summarise,
                                    fixed_objects = sim_pars,
                                    parallel = TRUE,
                                    packages = c("tidyverse", 
                                                 "gimme",
                                                 "mlVAR",
                                                 "graphicalVAR",
                                                 "lm.beta"),
                                    save_results = FALSE,
                                    ncores = 2,
                                    debug = "summarise"
                                    # filename = "centrality-simulation.rds",
                                    # save_seeds = TRUE
                                    )

SimClean()

```


# Visualization



